name: Run Flatpak Tests
on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      actions: write
      contents: write
      issues: read
      pull-requests: read

    name: Run Flatpak Tests - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            name: "Ubuntu x64"
    steps:
      - uses: actions/checkout@v2

      - name: Download Pragma nightly build
        run: |
          mkdir -p install
          wget https://github.com/Silverlan/pragma/releases/download/nightly/pragma-lin64.tar.gz \
            -O pragma-lin64.tar.gz

      - name: Extract Pragma into install/
        run: |
          tar -xzf pragma-lin64.tar.gz -C install
          rm pragma-lin64.tar.gz

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Add Flathub remote (user)
        run: |
          flatpak --user remote-add --if-not-exists flathub \
            https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build Flatpak Package
        run: |
          flatpak-builder \
            --force-clean \
            --user \
            --install-deps-from=flathub \
            --repo=repo \
            builddir io.github.silverlan.pfm.yml

      - name: Add Flatpak Repo
        run: |
          flatpak --user remote-add --no-gpg-verify pfm-local repo

      - name: Install Flatpak Package
        run: |
          flatpak --user install --reinstall --assumeyes --noninteractive pfm-local io.github.silverlan.pfm

      - name: Run Flatpak Package
        run: |
          flatpak --user run io.github.silverlan.pfm -- -log 2 2
