name: Run Flatpak Tests
on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      actions: write
      contents: write
      issues: read
      pull-requests: read

    name: Run Flatpak Tests - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            name: "Ubuntu x64"
    steps:
      - uses: actions/checkout@v2

      - name: Install Flatpak and Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Build Flatpak Package
        run: |
          flatpak-builder \
            --force-clean \
            --user \
            --install-deps-from=flathub \
            --repo=repo \
            builddir io.github.silverlan.pfm.yml

      - name: Add Flatpak Repo
        run: |
          flatpak --user remote-add --no-gpg-verify pfm-local repo

      - name: Install Flatpak Package
        run: |
          flatpak --user install --reinstall pfm-local io.github.silverlan.pfm

      - name: Run Flatpak Package
        run: |
          flatpak --user run io.github.silverlan.pfm -- -log 2 2
