name: Tests
on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      actions: write
      contents: write
      issues: read
      pull-requests: read

    name: Run Flatpak Tests - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            name: "Ubuntu x64"
    steps:
      - uses: actions/checkout@v2

      - name: Download Pragma nightly build
        run: |
          mkdir -p install
          wget https://github.com/Silverlan/pragma/releases/download/nightly/pragma-lin64.tar.gz \
            -O pragma-lin64.tar.gz
          tar -xzf pragma-lin64.tar.gz -C install --strip-components=1

      - name: Copy Override Files
        shell: bash
        run: |
          # Ensure install directory exists
          mkdir -p install

          if [ -d override ]; then
            echo "Copying override files into install/…"
            # Copy all files (including hidden), preserving attributes, and overwrite
            cp -a override/. install/
          else
            echo "No override directory found; nothing to copy."
          fi

      - name: Download Additional Overrides
        shell: bash
        run: |
          cd install
          wget https://landing.pragma-engine.com/share/base.lua -O lua/tests/base.lua

      - name: Run Tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: pragma-tests-ci.yml
          inputs: '{ "os": "ubuntu" }'
