name: Tests
on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      actions: write
      contents: write
      issues: read
      pull-requests: read

    name: Run Flatpak Tests - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
            name: "Ubuntu x64"
    steps:
      - uses: actions/checkout@v2

      - name: Download Pragma nightly build
        run: |
          mkdir -p install
          wget https://github.com/Silverlan/pragma/releases/download/nightly/pragma-lin64.tar.gz \
            -O pragma-lin64.tar.gz

      - name: Run Tests
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: pragma-tests-ci.yml
          inputs: '{ "os": "ubuntu" }'
